# HCM estimate penetrance (aggregate)

```{r}
HCMx <- read.table("HCMx.txt", header=T, sep="\t") #before penetrance filter
HCMx$REVEL <- as.numeric(as.character(HCMx$REVEL))
ukb <- read.table("ukb_hcm_match.txt", header=T, sep="\t")

#### All HCM vars
my <- HCMx
dim(my)
#1340
sum(my$AC_ALL_HCM)
#4314
max(my$AN_ALL_HCM)
#20800

dim(ukb)
#1735
sum(ukb$ukbAC_qced)
#9196
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=97, n_D=52660, x_AgD=4314, n_AgD=20800, x_A=9196, n_A=334956)
#0.01391561 (0.01138069-0.01701516)

#### All HCM female

my <- HCMx[which(HCMx$AN_HCM_female >0),]
dim(my)
#1340
sum(my$AC_HCM_female)
#527
max(my$AN_HCM_female)
#1468

#female
 hmm <- ukb[which(ukb$ukbAN_fem >0),]
 sum(hmm$ukbAC_fem)
#5039
max(hmm$ukbAN_fem)
#183502
dim(hmm)
#1735

penetrance(x_D=15, n_D=19646, x_AgD=527, n_AgD=1468, x_A=5039, n_A=183502)
#0.009986866 (0.00603896-0.01651568)

#### All HCM male
my <- HCMx[which(HCMx$AN_HCM_male >0),]
dim(my)
#1340
sum(my$AC_HCM_male)
#850
max(my$AN_HCM_male)
#2708

#male
hmm <- ukb[which(ukb$ukbAN_man >0),]
sum(hmm$ukbAC_man)
#4157
max(hmm$ukbAN_man)
#151454
dim(hmm)
#1735

penetrance(x_D=68, n_D=24411, x_AgD=850, n_AgD=2708, x_A=4157, n_A=151454)
#0.03185708 (0.02494006-0.04069251)

#### ALL HCM penetrance in people with sex
my <- HCMx[which(HCMx$AN_HCM_male >0 | HCMx$AN_HCM_female >0),]
dim(my)
#1340
sum(my$AC_HCM_male) + sum(my$AC_HCM_female) 
#1377
max(my$AN_HCM_male) + max(my$AN_HCM_female)
#4176

hmm <- ukb[which(ukb$ukbAN_man >0 | ukb$ukbAN_fem >0),]
sum(hmm$ukbAC_man) + sum(hmm$ukbAC_fem)
#9196
max(hmm$ukbAN_man) + max(hmm$ukbAN_fem) 
#334956
dim(hmm)
#1735

penetrance(x_D=97, n_D=52660, x_AgD=1377, n_AgD=4176, x_A=9196, n_A=334956)
#0.02212376 (0.01804172-0.02712938)

#### ALL EUR
my <- HCMx[which(HCMx$AN_HCM_EUR >0),]
dim(my)
#1340
sum(my$AC_HCM_EUR)
#3932
max(my$AN_HCM_EUR)
#19384

hmm <- ukb[which(ukb$ukbAN_eu >0),]
sum(hmm$ukbAC_eu)
#8068
max(hmm$ukbAN_eu)
#310054
dim(hmm)
#1735

penetrance(x_D=97, n_D=52660, x_AgD=3932, n_AgD=19384, x_A=8068, n_A=310054)
#0.01435946 (0.01173988-0.01756357)

####ALL AFR
my <- HCMx[which(HCMx$AN_HCM_AFR >0),]
dim(my)
#1340
sum(my$AC_HCM_AFR)
#296
max(my$AN_HCM_AFR)
#984

hmm <- ukb[which(ukb$ukbAN_afr >0),]
sum(hmm$ukbAC_afr)
#254
max(hmm$ukbAN_afr)
#5806
dim(hmm)
#1735

penetrance(x_D=97, n_D=52660, x_AgD=296, n_AgD=984, x_A=254, n_A=5806)
#0.01266591 (0.009858047 - 0.01627353)

####ALL EAS
my <- HCMx[which(HCMx$AN_HCM_EAS >0),]
dim(my)
#1340
sum(my$AC_HCM_EAS)
#37
max(my$AN_HCM_EAS)
#172

hmm <- ukb[which(ukb$ukbAN_eas >0),]
sum(hmm$ukbAC_eas)
#63
max(hmm$ukbAN_eas)
#1210
dim(hmm)
#1735

penetrance(x_D=97, n_D=52660, x_AgD=37, n_AgD=172, x_A=63, n_A=1210)
#0.007610941 (0.004998257-0.01158932)

####ALL SAS
my <- HCMx[which(HCMx$AN_HCM_SAS >0),]
dim(my)
#1340
sum(my$AC_HCM_SAS)
#38
max(my$AN_HCM_SAS)
#204

hmm <- ukb[which(ukb$ukbAN_sas >0),]
sum(hmm$ukbAC_sas)
#316
max(hmm$ukbAN_sas)
#6272
dim(hmm)
#1735

penetrance(x_D=97, n_D=52660, x_AgD=38, n_AgD=204, x_A=316, n_A=6272)
#0.006810894 (0.004737069-0.00979261)

### HCM in those with ancestry data
my <- HCMx[which(HCMx$AN_HCM_SAS >0 | HCMx$AN_HCM_EUR >0 | HCMx$AN_HCM_EAS > 0 | HCMx$AN_HCM_AFR > 0),]
dim(my)
#1340
sum(my$AC_HCM_SAS) + sum(my$AC_HCM_EAS) + sum(my$AC_HCM_EUR) + sum(my$AC_HCM_AFR)
#4303
max(my$AN_HCM_SAS) + max(my$AN_HCM_EAS) + max(my$AN_HCM_EUR) + max(my$AN_HCM_AFR)
#20744

hmm <- ukb[which(ukb$ukbAN_sas >0 | ukb$ukbAN_eas > 0 | ukb$ukbAN_afr >0 | ukb$ukbAN_eu >0),]
sum(hmm$ukbAC_sas) + sum(hmm$ukbAC_eas) + sum(hmm$ukbAC_afr) + sum(hmm$ukbAC_eu)
#8701
max(hmm$ukbAN_sas) + max(hmm$ukbAN_eas) + max(hmm$ukbAN_afr) + max(hmm$ukbAN_eu)
#323342
dim(hmm)
#1735

penetrance(x_D=97, n_D=52660, x_AgD=4303, n_AgD=20744, x_A=8701, n_A=323342)
#0.01419935 (0.01161201-0.01736318)

#### Age

#0s
penetrance(x_D=(97*(max(HCMx$AN_HCM_0s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_0s), n_AgD=max(HCMx$AN_HCM_0s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.0002726665 (8.317719e-05-0.0008938394)

#10s
penetrance(x_D=(97*(max(HCMx$AN_HCM_10s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_10s), n_AgD=max(HCMx$AN_HCM_10s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.002236989 (0.00119264-0.004195836)

#20s
penetrance(x_D=(97*(max(HCMx$AN_HCM_20s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_20s), n_AgD=max(HCMx$AN_HCM_20s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.004436637 (0.002754769-0.007145336)

#30s
penetrance(x_D=(97*(max(HCMx$AN_HCM_30s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_30s), n_AgD=max(HCMx$AN_HCM_30s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.008081258 (0.005601847-0.01165807)

#40s
penetrance(x_D=(97*(max(HCMx$AN_HCM_40s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_40s), n_AgD=max(HCMx$AN_HCM_40s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.01310356 (0.00983553-0.01745746)

#50s
penetrance(x_D=(97*(max(HCMx$AN_HCM_50s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_50s), n_AgD=max(HCMx$AN_HCM_50s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.01705098 (0.01337991-0.02172929)

#60s
penetrance(x_D=(97*(max(HCMx$AN_HCM_60s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_60s), n_AgD=max(HCMx$AN_HCM_60s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.02064575 (0.01663709-0.0256203)

#70s
penetrance(x_D=(97*(max(HCMx$AN_HCM_70s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_70s), n_AgD=max(HCMx$AN_HCM_70s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.02222478 (0.01808904-0.02730608)

#80s
penetrance(x_D=(97*(max(HCMx$AN_HCM_80s)/max(HCMx$AN_HCM_80s))), n_D=(52660), x_AgD=sum(HCMx$AC_HCM_80s), n_AgD=max(HCMx$AN_HCM_80s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.02252714 (0.0183692-0.02762626)

one1 <- c("by 10", 0.0002726665, 8.317719e-05, 0.0008938394, max(HCMx$AN_HCM_0s)/max(HCMx$AN_HCM_80s))
one2 <- c("by 20", 0.002236989, 0.00119264, 0.004195836, max(HCMx$AN_HCM_10s)/max(HCMx$AN_HCM_80s))
one3 <- c("by 30", 0.004436637, 0.002754769, 0.007145336, max(HCMx$AN_HCM_20s)/max(HCMx$AN_HCM_80s))
one <- c("by 40", 0.008081258, 0.005601847, 0.01165807, max(HCMx$AN_HCM_30s)/max(HCMx$AN_HCM_80s))
two <- c("by 50", 0.01310356, 0.00983553, 0.01745746, max(HCMx$AN_HCM_40s)/max(HCMx$AN_HCM_80s))
thre <- c("by 60", 0.01705098, 0.01337991, 0.02172929, max(HCMx$AN_HCM_50s)/max(HCMx$AN_HCM_80s))
four <- c("by 70", 0.02064575, 0.01663709, 0.0256203, max(HCMx$AN_HCM_60s)/max(HCMx$AN_HCM_80s))
five <- c("by 80", 0.02222478, 0.01808904, 0.02730608, max(HCMx$AN_HCM_70s)/max(HCMx$AN_HCM_80s))
five1 <- c("by 100", 0.02252714, 0.0183692, 0.02762626, max(HCMx$AN_HCM_80s)/max(HCMx$AN_HCM_80s))

one1 <- c("by 10", 0.0002726665, 8.317719e-05, 0.0008938394)
one2 <- c("by 20", 0.002236989, 0.00119264, 0.004195836)
one3 <- c("by 30", 0.004436637, 0.002754769, 0.007145336)
one <- c("by 40", 0.008081258, 0.005601847, 0.01165807)
two <- c("by 50", 0.01310356, 0.00983553, 0.01745746)
thre <- c("by 60", 0.01705098, 0.01337991, 0.02172929)
four <- c("by 70", 0.02064575, 0.01663709, 0.0256203)
five <- c("by 80", 0.02222478, 0.01808904, 0.02730608)
five1 <- c("by 100", 0.02252714, 0.0183692, 0.02762626)

okay <- rbind(one1,one2,one3,one,two,thre,four,five,five1)
#colnames(okay) <- c("Curation", "Penetrance", "LCI", "UCI", "prop")
colnames(okay) <- c("Curation", "Penetrance", "LCI", "UCI")
okay <- data.frame(okay)
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
#okay$prop <- (as.numeric(okay$prop)*0.02252714)
okay$order <- seq(1,nrow(okay))

#library(forcats)
c <- okay %>%
  mutate(ordering = rev(order),
         Curation = fct_reorder(Curation, ordering, .desc = T)) %>%
ggplot( aes(x=Curation, y=Penetrance)) + 
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.4)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.4), size=5) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
  ylab("Penetrance") +
  xlab("Variant") +
  ylim(0,0.03)+
  ggtitle("HCM")# +

### HCM in age cohort

my <- HCMx[which(HCMx$AN_HCM_0s >0 | HCMx$AN_HCM_10s >0 | HCMx$AN_HCM_20s > 0 | HCMx$AN_HCM_30s > 0 | HCMx$AN_HCM_40s >0 | HCMx$AN_HCM_50s >0 | HCMx$AN_HCM_60s >0 | HCMx$AN_HCM_70s >0 | HCMx$AN_HCM_80s>0),]
dim(my)
#1340
sum(my$AC_HCM_80s) #cumulative
#1341
max(my$AN_HCM_80s)
#3994

hmm <- ukb
sum(hmm$ukbAC_qced)
#9196
max(hmm$ukbAN_qced)
#334956
dim(hmm)
#1735

penetrance(x_D=97, n_D=52660, x_AgD=1341, n_AgD=3994, x_A=9196, n_A=334956)
#0.02252714 (0.0183692-0.02762626)

#######rarity
summary(HCMx$gnomADg_AC) # 1-92
none <- HCMx[is.na(HCMx$gnomADg_AC),]
one <- HCMx[which(HCMx$gnomADg_AC == 1),]
two <- HCMx[which(HCMx$gnomADg_AC == 2),]
three <- HCMx[which(HCMx$gnomADg_AC == 3),]
four <- HCMx[which(HCMx$gnomADg_AC == 4),]
five <- HCMx[which(HCMx$gnomADg_AC == 5),]
ftoe <- HCMx[which(HCMx$gnomADg_AC > 5 & HCMx$gnomADg_AC < 8),]
etot <- HCMx[which(HCMx$gnomADg_AC > 7 & HCMx$gnomADg_AC < 11),]
etotw <- HCMx[which(HCMx$gnomADg_AC > 10 & HCMx$gnomADg_AC < 21),]
twtoth <- HCMx[which(HCMx$gnomADg_AC > 20 & HCMx$gnomADg_AC < 141),]

ukb$gnomADg_AC <- as.integer(as.character(ukb$gnomADg_AC))
summary(as.integer(as.character(ukb$gnomADg_AC))) # 1-92
none2 <- ukb[is.na(ukb$gnomADg_AC),]
one2 <- ukb[which(ukb$gnomADg_AC == 1),]
two2 <- ukb[which(ukb$gnomADg_AC == 2),]
three2 <- ukb[which(ukb$gnomADg_AC == 3),]
four2 <- ukb[which(ukb$gnomADg_AC == 4),]
five2 <- ukb[which(ukb$gnomADg_AC == 5),]
ftoe2 <- ukb[which(ukb$gnomADg_AC > 5 & ukb$gnomADg_AC < 8),]
etot2 <- ukb[which(ukb$gnomADg_AC > 7 & ukb$gnomADg_AC < 11),]
etotw2 <- ukb[which(ukb$gnomADg_AC > 10 & ukb$gnomADg_AC < 21),]
twtoth2 <- ukb[which(ukb$gnomADg_AC > 20 & ukb$gnomADg_AC < 141),]

#AC=0 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(none$AC_ALL_HCM), n_AgD=max(none$AN_ALL_HCM), x_A=sum(none2$ukbAC_qced), n_A=max(none2$ukbAN_qced))
#0.03727329 (0.03025419-0.04592086)

#AC=1 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(one$AC_ALL_HCM), n_AgD=max(one$AN_ALL_HCM), x_A=sum(one2$ukbAC_qced), n_A=max(one2$ukbAN_qced))
#0.01831592 (0.01458007-0.02300902)

#AC=2 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(two$AC_ALL_HCM), n_AgD=max(two$AN_ALL_HCM), x_A=sum(two2$ukbAC_qced), n_A=max(two2$ukbAN_qced))
#0.01542251 (0.01200784-0.0198082)

#AC=3 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(three$AC_ALL_HCM), n_AgD=max(three$AN_ALL_HCM), x_A=sum(three2$ukbAC_qced), n_A=max(three2$ukbAN_qced))
#0.01960316 (0.01541343-0.02493174)

#AC=4 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(four$AC_ALL_HCM), n_AgD=max(four$AN_ALL_HCM), x_A=sum(four2$ukbAC_qced), n_A=max(four2$ukbAN_qced))
#0.02196391 (0.01706264-0.02827307)

#AC=5 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(five$AC_ALL_HCM), n_AgD=max(five$AN_ALL_HCM), x_A=sum(five2$ukbAC_qced), n_A=max(five2$ukbAN_qced))
#0.01005053 (0.007459804-0.01354101)

#AC=6-7 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(ftoe$AC_ALL_HCM), n_AgD=max(ftoe$AN_ALL_HCM), x_A=sum(ftoe2$ukbAC_qced), n_A=max(ftoe2$ukbAN_qced))
#0.007359102 (0.005662861-0.00956343)

#AC=8-10 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(etot$AC_ALL_HCM), n_AgD=max(etot$AN_ALL_HCM), x_A=sum(etot2$ukbAC_qced), n_A=max(etot2$ukbAN_qced))
#0.01082485 (0.008483144-0.01381297)

#AC=11-20 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(etotw$AC_ALL_HCM), n_AgD=max(etotw$AN_ALL_HCM), x_A=sum(etotw2$ukbAC_qced), n_A=max(etotw2$ukbAN_qced))
#0.004904673 (0.003862947-0.006227324)

#AC=21-140 in gnomAD
penetrance(x_D=97, n_D=52660, x_AgD=sum(twtoth$AC_ALL_HCM), n_AgD=max(twtoth$AN_ALL_HCM), x_A=sum(twtoth2$ukbAC_qced), n_A=max(twtoth2$ukbAN_qced))
#0.002959941 (0.002329424-0.003761122)

bag <- c("0", 0.03727329 ,0.03025419,0.04592086)
des <- c("1", 0.01831592 ,0.01458007,0.02300902)
dsp <- c("2", 0.01542251 ,0.01200784,0.0198082)
one <- c("3", 0.01960316 ,0.01541343,0.02493174)
two <- c("4", 0.02196391 ,0.01706264,0.02827307)
thre <- c("5", 0.01005053 ,0.007459804,0.01354101)
four <- c("6", 0.007359102 ,0.005662861,0.00956343)
five <- c("8", 0.01082485 ,0.008483144,0.01381297)
six <- c("11", 0.004904673 ,0.003862947,0.006227324)
sev <- c("21+", 0.002959941 ,0.002329424,0.003761122)

okay <- rbind(bag, des, dsp, one,two,thre,four,five,six, sev)
colnames(okay) <- c("gnomAD_AC", "Penetrance", "LCI", "UCI")
okay <- data.frame(okay)
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$order <- seq(nrow(okay),1)

#library(forcats)
b <- okay %>%
mutate(ordering = as.numeric(order),
        gnomAD_AC = fct_reorder(gnomAD_AC, ordering, .desc = T)) %>%
ggplot( aes(x=gnomAD_AC, y=Penetrance, group=gnomAD_AC)) + 
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.4)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.4), size=5) +
  theme_minimal() +
  theme(text = element_text(size=16), legend.position = "none") +
  ylab("Penetrance") +
  xlab("gnomAD AC") +
  ylim(0,0.05)+
  ggtitle("HCM")+
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) 
```

# DCM estimate penetrance (aggregate)

```{r}
#DCM
DCMx <- read.table("DCMx.txt", header=T, sep="\t") #before penetrance filter
ukb <- read.table("ukb_dcm_match.txt", header=T, sep="\t")
DCMx$REVEL <- as.numeric(as.character(DCMx$REVEL))

#### All DCM vars
my <- DCMx
dim(my)
#665
sum(my$AC_ALL_DCM)
#833
max(my$AN_ALL_DCM)
#5128

dim(ukb)
#4898
sum(ukb$ukbAC_qced)
#22232
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=833, n_AgD=5128, x_A=22232, n_A=334956)
# 0.01110665 (0.009465513-0.01303234)

#### All DCM female
my <- DCMx[which(DCMx$AN_DCM_female >0),]
dim(my)
#665
sum(my$AC_DCM_female)
#149
max(my$AN_DCM_female)
#680

# #female
 hmm <- ukb[which(ukb$ukbAN_fem >0),]
  sum(hmm$ukbAC_fem)
# #12243
 max(hmm$ukbAN_fem)
# #183502
 dim(hmm)
# #4898

penetrance(x_D=60, n_D=20316, x_AgD=149, n_AgD=680, x_A=12243, n_A=183502)
#0.009699751 (0.007263621-0.01295293)

#### All DCM male
my <- DCMx[which(DCMx$AN_DCM_male >0),]
dim(my)
#665
sum(my$AC_DCM_male)
#299
max(my$AN_DCM_male)
#1452

#male
hmm <- ukb[which(ukb$ukbAN_man >0),]
sum(hmm$ukbAC_man)
#9989
max(hmm$ukbAN_man)
#151454
dim(hmm)
#4898

penetrance(x_D=117, n_D=18687, x_AgD=299, n_AgD=1452, x_A=9989, n_A=151454)
#0.01954853 (0.01588646-0.02405476)

#### ALL DCM penetrance in people with sex
my <- DCMx[which(DCMx$AN_DCM_male >0 | DCMx$AN_DCM_female >0),]
dim(my)
#665
sum(my$AC_DCM_male) + sum(my$AC_DCM_female) 
#448
max(my$AN_DCM_male) + max(my$AN_DCM_female)
#2132

hmm <- ukb[which(ukb$ukbAN_man >0 | ukb$ukbAN_fem >0),]
sum(hmm$ukbAC_man) + sum(hmm$ukbAC_fem)
#22232
max(hmm$ukbAN_man) + max(hmm$ukbAN_fem) 
#334956
dim(hmm)
#4898

penetrance(x_D=177, n_D=39003, x_AgD=448, n_AgD=2132, x_A=22232, n_A=334956)
#0.01436737 (0.01213669-0.01700804)

#### ALL EUR
my <- DCMx[which(DCMx$AN_DCM_EUR >0),]
dim(my)
#665
sum(my$AC_DCM_EUR)
#649
max(my$AN_DCM_EUR)
#4454

hmm <- ukb[which(ukb$ukbAN_eu >0),]
sum(hmm$ukbAC_eu)
#18375
max(hmm$ukbAN_eu)
#310054
dim(hmm)
#4898

penetrance(x_D=177, n_D=39003, x_AgD=649, n_AgD=4454, x_A=18375, n_A=310054)
#0.01115788 (0.009473157-0.01314221)

####ALL AFR
my <- DCMx[which(DCMx$AN_DCM_AFR >0),]
dim(my)
#665
sum(my$AC_DCM_AFR)
#78
max(my$AN_DCM_AFR)
#284

hmm <- ukb[which(ukb$ukbAN_afr >0),]
sum(hmm$ukbAC_afr)
#1193
max(hmm$ukbAN_afr)
#5806
dim(hmm)
#4898

penetrance(x_D=177, n_D=39003, x_AgD=78, n_AgD=284, x_A=1193, n_A=5806)
#0.006065938 (0.004752608 - 0.007742192)

### TTN AFR
my <- DCMx[which(DCMx$AN_DCM_AFR >0 & DCMx$SYMBOL == "TTN"),]
dim(my)
#191
sum(my$AC_DCM_AFR)
#14
max(my$AN_DCM_AFR)
#284

hmm <- ukb[which(ukb$ukbAN_afr >0 & ukb$SYMBOL == "TTN"),]
sum(hmm$ukbAC_afr)
#23
max(hmm$ukbAN_afr)
#5806
dim(hmm)
#542

penetrance(x_D=177, n_D=39003, x_AgD=14, n_AgD=284, x_A=23, n_A=5806)
#0.05649367 (0.02919498 - 0.1093179)

### TTN EUR

my <- DCMx[which(DCMx$AN_DCM_EUR >0 & DCMx$SYMBOL == "TTN"),]
dim(my)
#191
sum(my$AC_DCM_EUR)
#179
max(my$AN_DCM_EUR)
#4454

hmm <- ukb[which(ukb$ukbAN_eu >0 & ukb$SYMBOL == "TTN"),]
sum(hmm$ukbAC_eu)
#875
max(hmm$ukbAN_eu)
#310054
dim(hmm)
#542

penetrance(x_D=177, n_D=39003, x_AgD=179, n_AgD=4454, x_A=875, n_A=310054)
#0.06462651 (0.05209583 - 0.08017121)

####ALL EAS
my <- DCMx[which(DCMx$AN_DCM_EAS >0),]
dim(my)
#665
sum(my$AC_DCM_EAS)
#61
max(my$AN_DCM_EAS)
#210

hmm <- ukb[which(ukb$ukbAN_eas >0),]
sum(hmm$ukbAC_eas)
#180
max(hmm$ukbAN_eas)
#1210
dim(hmm)
#4898

penetrance(x_D=177, n_D=39003, x_AgD=61, n_AgD=210, x_A=180, n_A=1210)
#0.008861596 (0.006633488-0.0118381)

####ALL SAS
my <- DCMx[which(DCMx$AN_DCM_SAS >0),]
dim(my)
#665
sum(my$AC_DCM_SAS)
#30
max(my$AN_DCM_SAS)
#116

hmm <- ukb[which(ukb$ukbAN_sas >0),]
sum(hmm$ukbAC_sas)
#970
max(hmm$ukbAN_sas)
#6272
dim(hmm)
#4898

penetrance(x_D=177, n_D=39003, x_AgD=30, n_AgD=116, x_A=970, n_A=6272)
#0.007589785 (0.005384308-0.01069865)

### DCM in those with ancestry data
my <- DCMx[which(DCMx$AN_DCM_SAS >0 | DCMx$AN_DCM_EUR >0 | DCMx$AN_DCM_EAS > 0 | DCMx$AN_DCM_AFR > 0),]
dim(my)
#665
sum(my$AC_DCM_SAS) + sum(my$AC_DCM_EAS) + sum(my$AC_DCM_EUR) + sum(my$AC_DCM_AFR)
#818
max(my$AN_DCM_SAS) + max(my$AN_DCM_EAS) + max(my$AN_DCM_EUR) + max(my$AN_DCM_AFR)
#5064

hmm <- ukb[which(ukb$ukbAN_sas >0 | ukb$ukbAN_eas > 0 | ukb$ukbAN_afr >0 | ukb$ukbAN_eu >0),]
sum(hmm$ukbAC_sas) + sum(hmm$ukbAC_eas) + sum(hmm$ukbAC_afr) + sum(hmm$ukbAC_eu)
#20718
max(hmm$ukbAN_sas) + max(hmm$ukbAN_eas) + max(hmm$ukbAN_afr) + max(hmm$ukbAN_eu)
#323342
dim(hmm)
#4898

penetrance(x_D=177, n_D=39003, x_AgD=818, n_AgD=5064, x_A=20718, n_A=323342)
#0.01144066 (0.009747506-0.01342791)

#### Age

#0s
penetrance(x_D=(177*(max(DCMx$AN_DCM_0s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_0s), n_AgD=max(DCMx$AN_DCM_0s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.0001830636 (4.379194e-05-0.0007652612)

#10s
penetrance(x_D=(177*(max(DCMx$AN_DCM_10s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_10s), n_AgD=max(DCMx$AN_DCM_10s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.0006084541 (0.0002498235-0.001481912)

#20s
penetrance(x_D=(177*(max(DCMx$AN_DCM_20s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_20s), n_AgD=max(DCMx$AN_DCM_20s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.002068576 (0.001228916-0.003481935)

#30s
penetrance(x_D=(177*(max(DCMx$AN_DCM_30s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_30s), n_AgD=max(DCMx$AN_DCM_30s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.003779147 (0.002603608-0.005485446)

#40s
penetrance(x_D=(177*(max(DCMx$AN_DCM_40s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_40s), n_AgD=max(DCMx$AN_DCM_40s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.006416843 (0.004907914-0.008389689)

#50s
penetrance(x_D=(177*(max(DCMx$AN_DCM_50s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_50s), n_AgD=max(DCMx$AN_DCM_50s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.009945921 (0.00805285-0.01228402)

#60s
penetrance(x_D=(177*(max(DCMx$AN_DCM_60s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_60s), n_AgD=max(DCMx$AN_DCM_60s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.01261949 (0.01050649-0.01515745)

#70s
penetrance(x_D=(177*(max(DCMx$AN_DCM_70s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_70s), n_AgD=max(DCMx$AN_DCM_70s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.01365327 (0.01148092-0.01623667)

#80s
penetrance(x_D=(177*(max(DCMx$AN_DCM_80s)/max(DCMx$AN_DCM_80s))), n_D=(39003), x_AgD=sum(DCMx$AC_DCM_80s), n_AgD=max(DCMx$AN_DCM_80s), x_A=sum(ukb$ukbAC_qced), n_A=max(ukb$ukbAN_qced))
#0.01383151 (0.01164563-0.01642769)

one1 <- c("by 10", 0.0001830636, 4.379194e-05, 0.0007652612)
one2 <- c("by 20", 0.0006084541, 0.0002498235, 0.001481912)
one3 <- c("by 30", 0.002068576, 0.001228916, 0.003481935)
one <- c("by 40", 0.003779147, 0.002603608, 0.005485446)
two <- c("by 50", 0.006416843, 0.004907914, 0.008389689)
thre <- c("by 60", 0.009945921, 0.00805285, 0.01228402)
four <- c("by 70", 0.01261949, 0.01050649, 0.01515745)
five <- c("by 80", 0.01365327, 0.01148092, 0.01623667)
five1 <- c("by 100", 0.01383151, 0.01164563, 0.01642769)

okay <- rbind(one1,one2,one3,one,two,thre,four,five,five1)
colnames(okay) <- c("Curation", "Penetrance", "LCI", "UCI")
okay <- data.frame(okay)
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$order <- seq(1,nrow(okay))

#library(forcats)
f <- okay %>%
  mutate(ordering = rev(order),
         Curation = fct_reorder(Curation, ordering, .desc = T)) %>%
ggplot( aes(x=Curation, y=Penetrance)) + 
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.4, position = position_dodge(width = 0.4)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.4), size=4) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
  ylab("Penetrance") +
  xlab("Age (years)") +
  ylim(0,0.02)+
  ggtitle("DCM") 
 
library(ggpubr)
ggarrange(a + rremove("x.text") +rremove("xlab"), b, ncol = 1, nrow = 2, heights=c(0.1,0.1), align='v')

### DCM in age cohort
my <- DCMx[which(DCMx$AN_DCM_0s >0 | DCMx$AN_DCM_10s >0 | DCMx$AN_DCM_20s > 0 | DCMx$AN_DCM_30s > 0 | DCMx$AN_DCM_40s >0 | DCMx$AN_DCM_50s >0 | DCMx$AN_DCM_60s >0 | DCMx$AN_DCM_70s >0 | DCMx$AN_DCM_80s>0),]
dim(my)
#665
sum(my$AC_DCM_80s) #cumulative
#388
max(my$AN_DCM_80s)
#1918

hmm <- ukb
sum(hmm$ukbAC_qced)
#22232
max(hmm$ukbAN_qced)
#334956
dim(hmm)
#4898

penetrance(x_D=177, n_D=39003, x_AgD=388, n_AgD=1918, x_A=22232, n_A=334956)
#0.01383151 (0.01164563-0.01642769)

#variant consequences - NMDi 
my <- DCMx[which(DCMx$NMD == "NMD_escaping_variant"),]
dim(my)
#88
sum(my$AC_ALL_DCM)
#102
max(my$AN_ALL_DCM)
#5128

 hmm <- ukb[which(ukb$NMD == "NMD_escaping_variant"),]
 sum(hmm$ukbAC_qced)
# #548
 max(hmm$ukbAN_qced)
# #334956
 dim(hmm)
# #316

penetrance(x_D=177, n_D=39003, x_AgD=102, n_AgD=5128, x_A=548, n_A=334956)
#0.05517487 (0.04273589-0.07123443)

#######rarity
summary(DCMx$gnomADg_AC) # 1-139.00
none <- DCMx[is.na(DCMx$gnomADg_AC),]
one <- DCMx[which(DCMx$gnomADg_AC == 1),]
two <- DCMx[which(DCMx$gnomADg_AC == 2),]
three <- DCMx[which(DCMx$gnomADg_AC == 3),]
four <- DCMx[which(DCMx$gnomADg_AC == 4),]
five <- DCMx[which(DCMx$gnomADg_AC == 5),]
ftoe <- DCMx[which(DCMx$gnomADg_AC > 5 & DCMx$gnomADg_AC < 8),]
etot <- DCMx[which(DCMx$gnomADg_AC > 7 & DCMx$gnomADg_AC < 11),]
etotw <- DCMx[which(DCMx$gnomADg_AC > 10 & DCMx$gnomADg_AC < 21),]
twtoth <- DCMx[which(DCMx$gnomADg_AC > 20 & DCMx$gnomADg_AC < 141),]

ukb$gnomADg_AC <- as.integer(as.character(ukb$gnomADg_AC))
summary(as.integer(as.character(ukb$gnomADg_AC))) # 1-139.000
none2 <- ukb[is.na(ukb$gnomADg_AC),]
one2 <- ukb[which(ukb$gnomADg_AC == 1),]
two2 <- ukb[which(ukb$gnomADg_AC == 2),]
three2 <- ukb[which(ukb$gnomADg_AC == 3),]
four2 <- ukb[which(ukb$gnomADg_AC == 4),]
five2 <- ukb[which(ukb$gnomADg_AC == 5),]
ftoe2 <- ukb[which(ukb$gnomADg_AC > 5 & ukb$gnomADg_AC < 8),]
etot2 <- ukb[which(ukb$gnomADg_AC > 7 & ukb$gnomADg_AC < 11),]
etotw2 <- ukb[which(ukb$gnomADg_AC > 10 & ukb$gnomADg_AC < 21),]
twtoth2 <- ukb[which(ukb$gnomADg_AC > 20 & ukb$gnomADg_AC < 141),]

#AC=0 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(none$AC_ALL_DCM), n_AgD=max(none$AN_ALL_DCM), x_A=sum(none2$ukbAC_qced), n_A=max(none2$ukbAN_qced))
#0.03023825 (0.02543394-0.03595006)

#AC=1 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(one$AC_ALL_DCM), n_AgD=max(one$AN_ALL_DCM), x_A=sum(one2$ukbAC_qced), n_A=max(one2$ukbAN_qced))
#0.01206737 (0.009305428-0.01564908)

#AC=2 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(two$AC_ALL_DCM), n_AgD=max(two$AN_ALL_DCM), x_A=sum(two2$ukbAC_qced), n_A=max(two2$ukbAN_qced))
#0.008365015 (0.005950548-0.01175916)

#AC=3 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(three$AC_ALL_DCM), n_AgD=max(three$AN_ALL_DCM), x_A=sum(three2$ukbAC_qced), n_A=max(three2$ukbAN_qced))
#0.006023212 (0.004020636-0.009023219)

#AC=4 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(four$AC_ALL_DCM), n_AgD=max(four$AN_ALL_DCM), x_A=sum(four2$ukbAC_qced), n_A=max(four2$ukbAN_qced))
#0.004845384 (0.002827329-0.008303858)

#AC=5 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(five$AC_ALL_DCM), n_AgD=max(five$AN_ALL_DCM), x_A=sum(five2$ukbAC_qced), n_A=max(five2$ukbAN_qced))
#0.007738987 (0.00482584-0.01241067)

#AC=6-7 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(ftoe$AC_ALL_DCM), n_AgD=max(ftoe$AN_ALL_DCM), x_A=sum(ftoe2$ukbAC_qced), n_A=max(ftoe2$ukbAN_qced))
#0.004738421 (0.002961176-0.007582337)

#AC=8-10 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(etot$AC_ALL_DCM), n_AgD=max(etot$AN_ALL_DCM), x_A=sum(etot2$ukbAC_qced), n_A=max(etot2$ukbAN_qced))
#0.003310089 (0.001965882-0.00557342)

#AC=11-20 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(etotw$AC_ALL_DCM), n_AgD=max(etotw$AN_ALL_DCM), x_A=sum(etotw2$ukbAC_qced), n_A=max(etotw2$ukbAN_qced))
#0.004320185 (0.003089112-0.006041865)

#AC=21-140 in gnomAD
penetrance(x_D=177, n_D=39003, x_AgD=sum(twtoth$AC_ALL_DCM), n_AgD=max(twtoth$AN_ALL_DCM), x_A=sum(twtoth2$ukbAC_qced), n_A=max(twtoth2$ukbAN_qced))
#0.005539311 (0.004367208-0.007025993)

bag <- c("0", 0.03023825, 0.02543394, 0.03595006)
des <- c("1", 0.01206737, 0.009305428, 0.01564908)
dsp <- c("2", 0.008365015, 0.005950548, 0.01175916)
one <- c("3", 0.006023212, 0.004020636, 0.009023219)
two <- c("4", 0.004845384, 0.002827329, 0.008303858)
thre <- c("5", 0.007738987, 0.00482584, 0.01241067)
four <- c("6", 0.004738421, 0.002961176, 0.007582337)
five <- c("8", 0.003310089, 0.001965882, 0.00557342)
six <- c("11", 0.004320185, 0.003089112, 0.006041865)
sev <- c("21+", 0.005539311, 0.004367208, 0.007025993)

okay <- rbind(bag, des, dsp, one,two,thre,four,five,six, sev)
colnames(okay) <- c("gnomAD_AC", "Penetrance", "LCI", "UCI")
okay <- data.frame(okay)
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$order <- seq(nrow(okay),1)

#library(forcats)
e <- okay %>%
mutate(ordering = as.numeric(order),
        gnomAD_AC = fct_reorder(gnomAD_AC, ordering, .desc = T)) %>%
ggplot( aes(x=gnomAD_AC, y=Penetrance, group=gnomAD_AC)) + 
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.4)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.4), size=5) +
  theme_minimal() +
  theme(text = element_text(size=16), legend.position = "none") +
  ylab("Penetrance") +
  xlab("gnomAD AC") +
  ylim(0,0.04)+
  ggtitle("DCM") +
        scale_x_discrete(guide = guide_axis(n.dodge = 2)) 

ggarrange(a + rremove("x.text") +rremove("xlab"), b, ncol = 1, nrow = 2, heights=c(0.1,0.12), align='v')
```

# aggregate - HCM and DCM by Gene + Conseq

```{r}
HCMx <- read.table("HCMx.txt", header=T, sep="\t") #before penetrance filter
HCMx$REVEL <- as.numeric(as.character(HCMx$REVEL))
ukb <- read.table("ukb_hcm_match.txt", header=T, sep="\t")

#### GENES
table(HCMx$Consequence)
table(ukb$Consequence)

genelist <- c("MYBPC3", "MYH7", "MYL2", "MYL3", "TNNT2", "TPM1", "TNNI3", "ACTC1")

#First script - cases
df <- data.frame("test", "test", "0", "0", "0")
colnames(df) <- c("Gene", "Variants", "AC_ALL_HCM", "AN_ALL_HCM", "count")

for (gene in genelist){
hmm <- HCMx[which(HCMx$SYMBOL == gene),]

#splice + splice ai pass
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df[(nrow(df)+1),] <- data.frame(gene, "splice region (SpliceAI>=0.80)", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#splice + splice ai fail
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "FAIL" | SpliceAI_cutoff == "-")
df[(nrow(df)+1),] <- data.frame(gene, "splice region (SpliceAI<0.80)", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                   Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-") 
df[(nrow(df)+1),] <- data.frame(gene, "PTCs", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

# NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df[(nrow(df)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#missense etc + revel pass
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant") %>%
  filter(REVEL >= 0.75)
df[(nrow(df)+1),] <- data.frame(gene, "missense (REVEL>=0.75)", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#missense etc + revel fail
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant" ) %>%
  filter(REVEL < 0.75 | is.na(REVEL))
df[(nrow(df)+1),] <- data.frame(gene, "missense (REVEL<0.75)", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#other PAV
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df[(nrow(df)+1),] <- data.frame(gene, "other PAV", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))
}

#Second script - UKB
df_ukb <- data.frame("test", "test", "0", "0", "0")
colnames(df_ukb) <- c("Gene", "Variants", "ukbAC_qced", "ukbAN_qced", "count")

for (gene in genelist){
hmm <- ukb[which(ukb$SYMBOL == gene),]

#splice ai pass
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "splice region (SpliceAI>=0.80)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#splice ai fail
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "FAIL" | SpliceAI_cutoff == "-")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "splice region (SpliceAI<0.80)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

# NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#missense etc + revel pass
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant") %>%
  filter(REVEL >= 0.75)
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "missense (REVEL>=0.75)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#missense etc + revel fail
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant" ) %>%
  filter(REVEL < 0.75 | is.na(REVEL))
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "missense (REVEL<0.75)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#other PAV
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "other PAV", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))
}

### stick together and estimate penetrance

done <- data.frame(df, df_ukb[3:5])
done <- done[!done$Gene == "test",]
done <- done[!(as.integer(as.character(done$AC_ALL_HCM))) < 2,]
done <- done[!(as.integer(as.character(done$ukbAC_qced))) < 2,]

done[(ncol(done)+1):(ncol(done)+3)] <- penetrance(x_D=97, n_D=52660, 
                                                  x_AgD=(as.integer(as.character(done$AC_ALL_HCM))), n_AgD=(as.integer(as.character(done$AN_ALL_HCM))), 
                                                  x_A=(as.integer(as.character(done$ukbAC_qced))), n_A=(as.integer(as.character(done$ukbAN_qced))))
colnames(done)[(ncol(done)-2):(ncol(done))] <- c("Penetrance", "LCI", "UCI")
okay <- done
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$Type <- ""
okay$Type[okay$Variants == "splice region (SpliceAI>=0.80)"] <- "LoF"
okay$Type[okay$Variants == "splice region (SpliceAI<0.80)"] <- "LoF"
okay$Type[okay$Variants == "PTCs"] <- "LoF"
okay$Type[okay$Variants == "NMDi PTCs"] <- "non-LoF"
okay$Type[okay$Variants == "missense (REVEL>=0.75)"] <- "non-LoF"
okay$Type[okay$Variants == "missense (REVEL<0.75)"] <- "non-LoF"
okay$Type[okay$Variants == "other PAV"] <- "non-LoF"

#library(forcats)
a <- okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance") +   
  xlab("Gene") +
  coord_cartesian(ylim=c(0,1)) +
  ggtitle("HCM") +
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
  scale_shape_manual(values = c(0, 15, 16, 18, 1, 2, 17))+
 guides(shape=guide_legend(nrow=4))

b <- okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#, axis.text.x = element_text(size=12, angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance") +   
  xlab("Gene") +
  coord_cartesian(ylim=c(0,0.2)) +
  ggtitle("HCM zoom")+
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
  scale_shape_manual(values = c(0, 15, 16, 18, 1, 2, 17))

library(ggpubr)
ggpubr::ggarrange(a + rremove("xlab") + rremove("x.text"), b + rremove("xlab"), ncol = 1, nrow = 2, align = "v",  heights=c(0.1,0.12), common.legend = TRUE, legend = "bottom")

############################

#DCM
DCMx <- read.table("DCMx.txt", header=T, sep="\t") #before penetrance filter
ukb <- read.table("ukb_dcm_match.txt", header=T, sep="\t")
DCMx$REVEL <- as.numeric(as.character(DCMx$REVEL))

## TTNtvs alone
my <- DCMx[which(DCMx$SYMBOL == "TTN"),]
my2 <- ukb[which(ukb$SYMBOL == "TTN"),]
penetrance(x_D=177, n_D=39003, sum(my$AC_ALL_DCM), max(my$AN_ALL_DCM), sum(my2$ukbAC_qced), max(my2$ukbAN_qced))
#0.09837075 (0.08010638-0.1207994)

#### GENES
table(DCMx$Consequence)
table(ukb$Consequence)

genelist <- c("TTN", "BAG3", "DES", "LMNA", "MYH7", "PLN", "RBM20", "SCN5A", "TNNC1", "TNNT2", "DSP")

#First script - cases
df <- data.frame("test", "test", "0", "0", "0")
colnames(df) <- c("Gene", "Variants", "AC_ALL_DCM", "AN_ALL_DCM", "count")

for (gene in genelist){
hmm <- DCMx[which(DCMx$SYMBOL == gene),]

# splice ai pass
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df[(nrow(df)+1),] <- data.frame(gene, "splice region (SpliceAI>=0.80)", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#splice ai fail
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "FAIL" | SpliceAI_cutoff == "-")
df[(nrow(df)+1),] <- data.frame(gene, "splice region (SpliceAI<0.80)", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant"|
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-")
df[(nrow(df)+1),] <- data.frame(gene, "PTCs", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df[(nrow(df)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#missense etc + revel pass
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant") %>%
  filter(REVEL >= 0.75)
df[(nrow(df)+1),] <- data.frame(gene, "missense (REVEL>=0.75)", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#missense etc + revel fail
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant" ) %>%
  filter(REVEL < 0.75 | is.na(REVEL))
df[(nrow(df)+1),] <- data.frame(gene, "missense (REVEL<0.75)", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#other PAVs
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df[(nrow(df)+1),] <- data.frame(gene, "other PAV", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))
}

#Second script - UKB
df_ukb <- data.frame("test", "test", "0", "0", "0")
colnames(df_ukb) <- c("Gene", "Variants", "ukbAC_qced", "ukbAN_qced", "count")

for (gene in genelist){
hmm <- ukb[which(ukb$SYMBOL == gene),]

#splice ai pass
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "splice region (SpliceAI>=0.80)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#splice ai fail
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "FAIL" | SpliceAI_cutoff == "-")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "splice region (SpliceAI<0.80)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                   Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#missense etc + revel pass
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant") %>%
  filter(REVEL >= 0.75)
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "missense (REVEL>=0.75)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#missense etc + revel fail
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant" ) %>%
  filter(REVEL < 0.75 | is.na(REVEL))
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "missense (REVEL<0.75)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#other PAVs
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "other PAV", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))
}

### stick together and estimate penetrance

done <- data.frame(df, df_ukb[3:5])
done <- done[!done$Gene == "test",]
done <- done[!(as.integer(as.character(done$AC_ALL_DCM))) < 2,]
done <- done[!(as.integer(as.character(done$ukbAC_qced))) < 2,]

done[(ncol(done)+1):(ncol(done)+3)] <- penetrance(x_D=177, n_D=39003, 
                                                  x_AgD=(as.integer(as.character(done$AC_ALL_DCM))), n_AgD=(as.integer(as.character(done$AN_ALL_DCM))), 
                                                  x_A=(as.integer(as.character(done$ukbAC_qced))), n_A=(as.integer(as.character(done$ukbAN_qced))))
colnames(done)[(ncol(done)-2):(ncol(done))] <- c("Penetrance", "LCI", "UCI")
okay <- done
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$Gene[okay$Gene == "TTN"] <- "TTN*"
okay$Type <- ""
okay$Type[okay$Variants == "splice region (SpliceAI>=0.80)"] <- "LoF"
okay$Type[okay$Variants == "splice region (SpliceAI<0.80)"] <- "LoF"
okay$Type[okay$Variants == "PTCs"] <- "LoF"
okay$Type[okay$Variants == "NMDi PTCs"] <- "non-LoF"
okay$Type[okay$Variants == "missense (REVEL>=0.75)"] <- "non-LoF"
okay$Type[okay$Variants == "missense (REVEL<0.75)"] <- "non-LoF"
okay$Type[okay$Variants == "other PAV"] <- "non-LoF"

library(forcats)
c <- okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=15), legend.title = element_text(size=10), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#, axis.text.x = element_text(size=12, angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance and 95% CI") +   
  xlab("Gene") +
   coord_cartesian(ylim=c(0,1)) +
 ggtitle("DCM")+
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
  scale_shape_manual(values = c(0, 15, 16, 18, 1, 2, 17))

d <- okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=15), legend.title = element_text(size=10), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#, axis.text.x = element_text(size=12, angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance and 95% CI") +   
  xlab("Gene") +
   coord_cartesian(ylim=c(0,0.2)) +
 ggtitle("DCM zoom")+
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
  scale_shape_manual(values = c(0, 15, 16, 18, 1, 2, 17))

ggpubr::ggarrange(a + rremove("xlab") + rremove("x.text"),  c + rremove("xlab") + rremove("x.text") + rremove("ylab"), b + rremove("xlab"), d + rremove("xlab") + rremove("ylab"), ncol = 2, nrow = 2, align = "v",  heights=c(0.1,0.125), common.legend = TRUE, legend = "bottom")

ggarrange(c + rremove("xlab") + rremove("x.text") + rremove("ylab"), d + rremove("xlab") + rremove("ylab"), ncol = 1, nrow = 2, align = "v",  heights=c(0.1,0.125), common.legend = TRUE, legend = "bottom")
```

# aggregate - HCM and DCM by Gene + Conseq - shorter - Figure 2

```{r}
HCMx <- read.table("HCMx.txt", header=T, sep="\t") #before penetrance filter
HCMx$REVEL <- as.numeric(as.character(HCMx$REVEL))
ukb <- read.table("ukb_hcm_match.txt", header=T, sep="\t")

#### GENES
table(HCMx$Consequence)
table(ukb$Consequence)

genelist <- c("MYBPC3", "MYH7", "MYL2", "MYL3", "TNNT2", "TPM1", "TNNI3", "ACTC1")

#First script - cases
df <- data.frame("test", "test", "0", "0", "0")
colnames(df) <- c("Gene", "Variants", "AC_ALL_HCM", "AN_ALL_HCM", "count")

for (gene in genelist){
hmm <- HCMx[which(HCMx$SYMBOL == gene),]

#splice pass >0.8
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df[(nrow(df)+1),] <- data.frame(gene, "splice region", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                   Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-") 
df[(nrow(df)+1),] <- data.frame(gene, "PTCs", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

# NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df[(nrow(df)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#missense
lof1 <- hmm %>% filter(Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant")
df[(nrow(df)+1),] <- data.frame(gene, "missense", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))

#other PAV
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df[(nrow(df)+1),] <- data.frame(gene, "other PAV", sum(lof1$AC_ALL_HCM), max(lof1$AN_ALL_HCM), nrow(lof1))
}

#Second script - UKB
df_ukb <- data.frame("test", "test", "0", "0", "0")
colnames(df_ukb) <- c("Gene", "Variants", "ukbAC_qced", "ukbAN_qced", "count")

for (gene in genelist){
hmm <- ukb[which(ukb$SYMBOL == gene),]

#splice
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "splice region (SpliceAI>=0.80)", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

# NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#missense
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "missense", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#other PAV
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "other PAV", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))
}

### stick together and estimate penetrance

done <- data.frame(df, df_ukb[3:5])
done <- done[!done$Gene == "test",]
done <- done[!(as.integer(as.character(done$AC_ALL_HCM))) < 2,]
done <- done[!(as.integer(as.character(done$ukbAC_qced))) < 2,]

done[(ncol(done)+1):(ncol(done)+3)] <- penetrance(x_D=97, n_D=52660, 
                                                  x_AgD=(as.integer(as.character(done$AC_ALL_HCM))), n_AgD=(as.integer(as.character(done$AN_ALL_HCM))), 
                                                  x_A=(as.integer(as.character(done$ukbAC_qced))), n_A=(as.integer(as.character(done$ukbAN_qced))))
colnames(done)[(ncol(done)-2):(ncol(done))] <- c("Penetrance", "LCI", "UCI")
okay <- done
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$Type <- ""
okay$Type[okay$Variants == "splice region"] <- "LoF"
okay$Type[okay$Variants == "PTCs"] <- "LoF"
okay$Type[okay$Variants == "NMDi PTCs"] <- "non-LoF"
okay$Type[okay$Variants == "missense"] <- "non-LoF"
okay$Type[okay$Variants == "other PAV"] <- "non-LoF"
okay$Variants[okay$Variants == "splice region"] <- "splice region, LoF"
okay$Variants[okay$Variants == "PTCs"] <- "PTCs, LoF"
okay$Variants[okay$Variants == "NMDi PTCs"] <- "NMDi PTCs, non-LoF"
okay$Variants[okay$Variants == "missense"] <- "missense, non-LoF"
okay$Variants[okay$Variants == "other PAV"] <- "other PAV, non-LoF"

culr <- c("cornflowerblue", "cornflowerblue", "cornflowerblue", "darkturquoise","darkturquoise")

#library(forcats)    
a <- okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance") +   
  xlab("Gene") +
  coord_cartesian(ylim=c(0,1)) +
  ggtitle("HCM") +
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
  scale_shape_manual(values = c(17, 15, 16, 15, 18))+
 guides(shape=guide_legend(nrow=2))+
labs(color=NULL, shape=NULL)

b <-  okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance") +   
  xlab("Gene") +
  coord_cartesian(ylim=c(0,0.2)) +
  ggtitle("HCM zoom") +
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
  scale_shape_manual(values = c(17, 15, 16, 15, 18))+
 guides(shape=guide_legend(nrow=2))+
  labs(color = NULL, shape = NULL)

############################

#DCM
DCMx <- read.table("DCMx.txt", header=T, sep="\t") #before penetrance filter
ukb <- read.table("ukb_dcm_match.txt", header=T, sep="\t")
DCMx$REVEL <- as.numeric(as.character(DCMx$REVEL))

#### GENES
table(DCMx$Consequence)
table(ukb$Consequence)

genelist <- c("TTN", "BAG3", "DES", "LMNA", "MYH7", "PLN", "RBM20", "SCN5A", "TNNC1", "TNNT2", "DSP")

#First script - cases
df <- data.frame("test", "test", "0", "0", "0")
colnames(df) <- c("Gene", "Variants", "AC_ALL_DCM", "AN_ALL_DCM", "count")

for (gene in genelist){
hmm <- DCMx[which(DCMx$SYMBOL == gene),]

# splice
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df[(nrow(df)+1),] <- data.frame(gene, "splice region", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant"|
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-")
df[(nrow(df)+1),] <- data.frame(gene, "PTCs", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df[(nrow(df)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#missense
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant")
df[(nrow(df)+1),] <- data.frame(gene, "missense", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))

#other PAVs
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df[(nrow(df)+1),] <- data.frame(gene, "other PAV", sum(lof1$AC_ALL_DCM), max(lof1$AN_ALL_DCM), nrow(lof1))
}

#Second script - UKB
df_ukb <- data.frame("test", "test", "0", "0", "0")
colnames(df_ukb) <- c("Gene", "Variants", "ukbAC_qced", "ukbAN_qced", "count")

for (gene in genelist){
hmm <- ukb[which(ukb$SYMBOL == gene),]

#splice
lof1 <- hmm %>% filter(Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant") %>%
          filter(NMD == "-") %>%
  filter(SpliceAI_cutoff == "PASS")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "splice region", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#NMDc PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                   Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "-")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#NMDi PTCs
lof1 <- hmm %>% filter(Consequence == "frameshift_variant" |
                   Consequence == "frameshift_variant,splice_region_variant" |
                  Consequence == "splice_acceptor_variant" |
                    Consequence == "splice_acceptor_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                    Consequence == "splice_confirmed" |
                  Consequence == "splice_donor_5th_base_variant,intron_variant" |
                   Consequence == "splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_donor_variant" |
                   Consequence == "splice_donor_variant,coding_sequence_variant" |
                   Consequence == "splice_donor_variant,splice_donor_5th_base_variant,coding_sequence_variant,intron_variant" |
                    Consequence == "splice_donor_variant,splice_donor_region_variant,coding_sequence_variant,intron_variant" |
                   Consequence == "splice_donor_variant,splice_donor_region_variant,intron_variant" |
                  Consequence == "splice_polypyrimidine_tract_variant,intron_variant" |
                  Consequence == "splice_region_variant,splice_polypyrimidine_tract_variant,intron_variant" |
                   Consequence == "splice_polypyrimidine_tract_variant,splice_region_variant,intron_variant" |
                   Consequence == "splice_region_variant,intron_variant" |
                    Consequence == "splice_region_variant,synonymous_variant" |
                  Consequence == "stop_gained" |
                   Consequence == "stop_gained,frameshift_variant" |
                   Consequence == "stop_gained,splice_region_variant") %>%
          filter(NMD == "NMD_escaping_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "NMDi PTCs", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#missense
lof1 <- hmm %>% filter(
                  Consequence == "missense_variant" |
                  Consequence == "missense_variant,splice_region_variant") 
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "missense", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))

#other PAVs
lof1 <- hmm %>% filter(Consequence == "inframe_deletion" |
                    Consequence == "inframe_deletion,splice_region_variant" |
                  Consequence == "inframe_insertion" |
                  Consequence == "start_lost" |
                    Consequence == "stop_lost" |
                    Consequence == "start_lost,splice_region_variant")
df_ukb[(nrow(df_ukb)+1),] <- data.frame(gene, "other PAV", sum(lof1$ukbAC_qced), max(lof1$ukbAN_qced), nrow(lof1))
}

### stick together and estimate penetrance

done <- data.frame(df, df_ukb[3:5])
done <- done[!done$Gene == "test",]
done <- done[!(as.integer(as.character(done$AC_ALL_DCM))) < 2,]
done <- done[!(as.integer(as.character(done$ukbAC_qced))) < 2,]

done[(ncol(done)+1):(ncol(done)+3)] <- penetrance(x_D=177, n_D=39003, 
                                                  x_AgD=(as.integer(as.character(done$AC_ALL_DCM))), n_AgD=(as.integer(as.character(done$AN_ALL_DCM))), 
                                                  x_A=(as.integer(as.character(done$ukbAC_qced))), n_A=(as.integer(as.character(done$ukbAN_qced))))
colnames(done)[(ncol(done)-2):(ncol(done))] <- c("Penetrance", "LCI", "UCI")
okay <- done
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$Gene[okay$Gene == "TTN"] <- "TTN*"
okay$Type <- ""
okay$Type[okay$Variants == "splice region"] <- "LoF"
okay$Type[okay$Variants == "PTCs"] <- "LoF"
okay$Type[okay$Variants == "NMDi PTCs"] <- "non-LoF"
okay$Type[okay$Variants == "missense"] <- "non-LoF"
okay$Type[okay$Variants == "other PAV"] <- "non-LoF"
okay$Variants[okay$Variants == "splice region"] <- "splice region, LoF"
okay$Variants[okay$Variants == "PTCs"] <- "PTCs, LoF"
okay$Variants[okay$Variants == "NMDi PTCs"] <- "NMDi PTCs, non-LoF"
okay$Variants[okay$Variants == "missense"] <- "missense, non-LoF"
okay$Variants[okay$Variants == "other PAV"] <- "other PAV, non-LoF"

#library(forcats)
c <- okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance") +   
  xlab("Gene") +
   coord_cartesian(ylim=c(0,1)) +
 ggtitle("DCM")+
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
   scale_shape_manual(values = c(17, 15, 16, 15, 18))

d <- okay %>%
  ggplot( aes(x=Gene, y=Penetrance, color=Type, shape=Variants)) +
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.5)) +
    geom_point(position = position_dodge(width = 0.5), size=3) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Penetrance") +   
  xlab("Gene") +
   coord_cartesian(ylim=c(0,0.2)) +
 ggtitle("DCM zoom")+
    theme(legend.position="top", legend.box="vertical", legend.margin=margin()) +
  scale_color_manual(values=c("darkturquoise","cornflowerblue") ) +
   scale_shape_manual(values = c(17, 15, 16, 15, 18))

ggarrange(a + rremove("xlab") + rremove("x.text"),  c + rremove("xlab") + rremove("x.text") + rremove("ylab"), b + rremove("xlab"), d + rremove("xlab") + rremove("ylab"), ncol = 2, nrow = 2, align = "v",  heights=c(0.1,0.125), common.legend = TRUE, legend = "bottom")
```

# aggregate - Pathogenicity curation

```{r}
HCM <- read.table("HCMx.txt", header=T, sep="\t")
DCM <- read.table("DCMx.txt", header=T, sep="\t")
hcm <- read.table("ukb_hcm_match.txt", header=T, sep="\t")
dcm <- read.table("ukb_dcm_match.txt", header=T, sep="\t")

### HCM
#e.g. pathogenic
my <- HCM[which(HCM$Curation == "P"),]
dim(my)
#173
sum(my$AC_ALL_HCM)
#1424
max(my$AN_ALL_HCM)
#20800 

ukb <- hcm[which(hcm$Curation == "P"),]
dim(ukb)
#30
sum(ukb$ukbAC_qced)
#188
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=97, n_D=52660, x_AgD=1424, n_AgD=20800, x_A=188, n_A=334956)
#0.2246838 (0.1750868-0.28833)

#e.g. LP
my <- HCM[which(HCM$Curation == "LP"),]
dim(my)
#316
sum(my$AC_ALL_HCM)
#1322
max(my$AN_ALL_HCM)
#20800 

ukb <- hcm[which(hcm$Curation == "LP"),]
dim(ukb)
#98
sum(ukb$ukbAC_qced)
#573
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=97, n_D=52660, x_AgD=1322, n_AgD=20800, x_A=573, n_A=334956)
#0.06843807 (0.0548813-0.08534362)

###################
### P/LP for comparison with JACC
#e.g. LP
my <- HCM[which(HCM$Curation == "LP" | HCM$Curation == "P"),]
dim(my)
#489
sum(my$AC_ALL_HCM)
#2746
max(my$AN_ALL_HCM)
#20800 

ukb <- hcm[which(hcm$Curation == "LP" | hcm$Curation == "P"),]
dim(ukb)
#128
sum(ukb$ukbAC_qced)
#761
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=97, n_D=52660, x_AgD=2746, n_AgD=20800, x_A=761, n_A=334956)
#0.1070377 (0.08646167-0.1325104)

#####
#e.g. VUS
my <- HCM[which(HCM$Curation == "VUS"),]
dim(my)
#832
sum(my$AC_ALL_HCM)
#1498
max(my$AN_ALL_HCM)
#20800 

ukb <- hcm[which(hcm$Curation == "VUS"),]
dim(ukb)
#1552
sum(ukb$ukbAC_qced)
#7622
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=97, n_D=52660, x_AgD=1498, n_AgD=20800, x_A=7622, n_A=334956)
#0.005829938 (0.004747342-0.007159412)

#e.g. LB
my <- HCM[which(HCM$Curation == "LB"),]
dim(my)
#19
sum(my$AC_ALL_HCM)
#70
max(my$AN_ALL_HCM)
#20800 

ukb <- hcm[which(hcm$Curation == "LB"),]
dim(ukb)
#53
sum(ukb$ukbAC_qced)
#772
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=97, n_D=52660, x_AgD=70, n_AgD=20800, x_A=772, n_A=334956)
#0.002689755 (0.001964929-0.003681954)

###try match SARC-IND JACC paper
my <- HCM[which(HCM$Curation == "LB" | HCM$Curation == "VUS"),]
dim(my)
#851
sum(my$AC_ALL_HCM)
#1568
max(my$AN_ALL_HCM)
#20800 

ukb <- hcm[which(hcm$Curation == "LB" | hcm$Curation == "VUS"),]
dim(ukb)
#1605
sum(ukb$ukbAC_qced)
#8394
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=97, n_D=52660, x_AgD=1568, n_AgD=20800, x_A=8394, n_A=334956)
#0.005541128 (0.00451393-0.006802076)

# NO Benign

#plot
one <- c("Pathogenic", 0.2246838 , 0.1750868, 0.28833)
thre <- c("Likely Pathogenic",        0.06843807 , 0.0548813, 0.08534362)
five <- c("Unknown Significance",       0.005829938 , 0.004747342, 0.007159412)
sev <- c("Benign / Likely Benign",         0.002689755 , 0.001964929, 0.003681954)
okay <- rbind(one,thre,five,sev)
colnames(okay) <- c("Curation", "Penetrance", "LCI", "UCI")
okay <- data.frame(okay)
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$Curation <- factor(okay$Curation, levels = c("Pathogenic", "Likely Pathogenic", "Unknown Significance", "Benign / Likely Benign"))

culr <- c("red", "orange", "lightgoldenrod4","darkgrey")
scaleFUN <- function(x) sprintf("%.2f", x)

library(forcats)
a <- okay %>% 
  mutate(ordering = (as.numeric(Penetrance)),
         Curation = fct_reorder(Curation, ordering, .desc = T)) %>%
ggplot( aes(x=Curation, y=Penetrance, color=Curation)) + 
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.4)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.4), size=5) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, color=culr)) +
  ylab("Penetrance") +
  ggtitle("HCM")+
 scale_color_manual(values=c("Pathogenic"="red", "Likely Pathogenic"="orange", "Unknown Significance"="lightgoldenrod4", "Benign / Likely Benign" = "darkgrey"), drop = FALSE)+
 theme(legend.position="none", legend.box="vertical")+
  scale_y_continuous(labels=scaleFUN)

################## DCM

#e.g. pathogenic
my <- DCM[which(DCM$Curation == "P"),]
dim(my)
#21
sum(my$AC_ALL_DCM)
#39
max(my$AN_ALL_DCM)
#5128 

ukb <- dcm[which(dcm$Curation == "P"),]
dim(ukb)
#22
sum(ukb$ukbAC_qced)
#59
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=39, n_AgD=5128, x_A=59, n_A=334956)
#0.1959517 (0.1278112-0.3004203)

#e.g. LP
my <- DCM[which(DCM$Curation == "LP"),]
dim(my)
#247
sum(my$AC_ALL_DCM)
#315
max(my$AN_ALL_DCM)
#5128 

ukb <- dcm[which(dcm$Curation == "LP"),]
dim(ukb)
#577
sum(ukb$ukbAC_qced)
#942
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=315, n_AgD=5128, x_A=942, n_A=334956)
#0.09912355 (0.08177105-0.1201584)

##### for analysis to other papers
#e.g. pathogenic
my <- DCM[which(DCM$Curation == "P" | DCM$Curation == "LP"),]
dim(my)
#268
sum(my$AC_ALL_DCM)
#354
max(my$AN_ALL_DCM)
#5128 

ukb <- dcm[which(dcm$Curation == "P" | dcm$Curation == "LP"),]
dim(ukb)
#599
sum(ukb$ukbAC_qced)
#1001
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=354, n_AgD=5128, x_A=1001, n_A=334956)
#0.1048302 (0.0868382-0.1265499)

####

#e.g. VUS
my <- DCM[which(DCM$Curation == "VUS"),]
dim(my)
#356
sum(my$AC_ALL_DCM)
#415
max(my$AN_ALL_DCM)
#5128 

ukb <- dcm[which(dcm$Curation == "VUS"),]
dim(ukb)
#4183
sum(ukb$ukbAC_qced)
#18429
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=415, n_AgD=5128, x_A=18429, n_A=334956)
#0.006675186 (0.005609769-0.007942948)

#e.g. LB
my <- DCM[which(DCM$Curation == "LB"),]
dim(my)
#37
sum(my$AC_ALL_DCM)
#56
max(my$AN_ALL_DCM)
#5128 

ukb <- dcm[which(dcm$Curation == "LB"),]
dim(ukb)
#109
sum(ukb$ukbAC_qced)
#2552
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=56, n_AgD=5128, x_A=2552, n_A=334956)
#0.006504908 (0.004816721-0.00878478)

# Benign
my <- DCM[which(DCM$Curation == "B"),]
dim(my)
#4
sum(my$AC_ALL_DCM)
#8
max(my$AN_ALL_DCM)
#5128 

ukb <- dcm[which(dcm$Curation == "B"),]
dim(ukb)
#7
sum(ukb$ukbAC_qced)
#250
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=8, n_AgD=5128, x_A=250, n_A=334956)
#0.009502722 (0.004725481-0.01910953)

### Benign or LB
my <- DCM[which(DCM$Curation == "B" | DCM$Curation == "LB"),]
dim(my)
#41
sum(my$AC_ALL_DCM)
#64
max(my$AN_ALL_DCM)
#5128 

ukb <- dcm[which(dcm$Curation == "B" | dcm$Curation == "LB"),]
dim(ukb)
#116
sum(ukb$ukbAC_qced)
#2802
max(ukb$ukbAN_qced)
#334956

penetrance(x_D=177, n_D=39003, x_AgD=64, n_AgD=5128, x_A=2802, n_A=334956)
#0.006770826 (0.005087423-0.00901126)

#plot
one <- c("Pathogenic",            0.1959517 , 0.1278112, 0.3004203)
thre <- c("Likely Pathogenic",    0.09912355 , 0.08177105, 0.1201584)
five <- c("Unknown Significance", 0.006675186 , 0.005609769, 0.007942948)
sev <- c("Benign / Likely Benign",0.006770826, 0.005087423, 0.00901126)
#eig <- c("Benign",                0.009502722 , 0.004725481, 0.01910953)

okay <- rbind(one,thre,five,sev)
colnames(okay) <- c("Curation", "Penetrance", "LCI", "UCI")
okay <- data.frame(okay)
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))
okay$order <- c(4,3,2,1)
scaleFUN <- function(x) sprintf("%.2f", x)

#library(forcats)
d <- okay %>%
  mutate(ordering = as.numeric(order),
         Curation = fct_reorder(Curation, ordering, .desc = T)) %>%
ggplot( aes(x=Curation, y=Penetrance, color=Curation)) + 
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.5, position = position_dodge(width = 0.4)) +
    geom_point(position = position_dodge(width = 0.4), size=5) +
  theme_minimal() +
  theme(text = element_text(size=16), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, color=culr, size=13), legend.position = "none") +
  ylab("Penetrance") +
  xlab("Variant curation") +
  ggtitle("DCM")+
   scale_color_manual(values=c("Benign / Likely Benign" = "grey", "Unknown Significance"="lightgoldenrod4", "Likely Pathogenic"="orange", "Pathogenic"="red"), drop = FALSE)+
  scale_y_continuous(labels=scaleFUN)

library(ggpubr)
ggarrange(a + rremove("xlab") + rremove("x.text"), b + rremove("xlab") + rremove("x.text"), ncol = 1, nrow = 2, align = "v",  heights=c(0.1,0.1), common.legend = TRUE, legend = "bottom")

####

thre <- c("LP", 0.3071534, 0.1904164, 0.4954573, "ALL")
four <- c("LP", 0.3305651, 0.194836, 0.5608474, "EUR")
five <- c("VUS", 0.02370721, 0.01803703, 0.0311599, "ALL")
six <- c("VUS", 0.0164344, 0.01151188, 0.0234618, "EUR")
sev <- c("LB", 0.0140806, 0.009502998, 0.02086323, "ALL")
eig <- c("LB", 0.01935581, 0.01101795, 0.03400336, "EUR")
one <- c("Benign", 0.01062347, 0.004819192, 0.02341846, "ALL")
okay <- rbind(thre,four,five,six,sev,eig,one)
colnames(okay) <- c("Curation", "Penetrance", "LCI", "UCI", "type")
okay <- data.frame(okay)
okay$Penetrance <- as.numeric(as.character(okay$Penetrance))
okay$UCI <- as.numeric(as.character(okay$UCI))
okay$LCI <- as.numeric(as.character(okay$LCI))

library(forcats)
okay %>%
  mutate(ordering = as.numeric(Penetrance),
         Curation = fct_reorder(Curation, ordering, .desc = T)) %>%
ggplot( aes(x=Curation, y=Penetrance, colour=type, group=type)) + 
  geom_errorbar(aes(ymin=LCI, ymax=UCI), width=.1, position = position_dodge(width = 0.4)) +
  # geom_line(position = position_dodge(width = 0.2)) +
    geom_point(position = position_dodge(width = 0.4), size=2) +
  theme_minimal() +
  theme(text = element_text(size=20), axis.text.x = element_text(size=12)) +
  ylab("Estimate of penetrance") +
  xlab("Variant") +
  ylim(0,1)+
  ggtitle("DCM")
```

# Figure 1

```{r}
#library(ggpubr)

ggarrange(a + rremove("x.text")+rremove("xlab"), b + rremove("x.text")+rremove("xlab")+rremove("ylab"), c + rremove("x.text")+rremove("xlab")+rremove("ylab"), d, e+rremove("ylab"), f+rremove("ylab"), ncol = 3, nrow = 2, align='v', heights=c(0.1,0.15))
```
